"""Add ru lang name

Revision ID: 0644ab9f6394
Revises: 17133e2017f3
Create Date: 2025-05-04 18:04:57.029541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0644ab9f6394'
down_revision: Union[str, None] = '17133e2017f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('languages', sa.Column('language_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('languages', 'language_name')
    # ### end Alembic commands ###
